import Sidebar from '@/components/Sidebar';
import './globals.css';
import { Figtree, Varela_Round } from 'next/font/google';

// const font = Figtree({ subsets: ['latin'] });
const font = Varela_Round({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Spotify - Music',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  );
}
